name: nostr-infra

services:
  relay1:
    image: nostr-rs-relay:local
    build:
      context: https://github.com/scsibug/nostr-rs-relay.git
    container_name: nostr-relay-1
    ports:
      - "8781:8080"
    volumes:
      - relay1-data:/usr/src/app/db
    networks:
      - nostr-net
    restart: unless-stopped

  relay2:
    image: nostr-rs-relay:local
    build:
      context: https://github.com/scsibug/nostr-rs-relay.git
    container_name: nostr-relay-2
    ports:
      - "8782:8080"
    volumes:
      - relay2-data:/usr/src/app/db
    networks:
      - nostr-net
    restart: unless-stopped

  nostrudel:
    image: ghcr.io/hzrd149/nostrudel:master
    container_name: nostr-strudel
    ports:
      - "8780:80"
    networks:
      - nostr-net
    restart: unless-stopped

volumes:
  relay1-data:
  relay2-data:

networks:
  nostr-net:
    external: true
